'use client';

import { useState, useEffect } from 'react';
import { API_BASE_URL, isPrecomputed } from '@/lib/runtime-config';

interface FeatureExample {
  activation: number;
  context: string;
}

interface DemoFeature {
  feature_idx: number;
  label: string;
  top_examples: FeatureExample[];
}

export default function FeatureBrowser() {
  const [featureIdx, setFeatureIdx] = useState('500');
  const [data, setData] = useState<{ feature_idx: number; examples: FeatureExample[] } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [demoFeatures, setDemoFeatures] = useState<DemoFeature[]>([]);
  const [demoMeta, setDemoMeta] = useState<{ limitations?: string } | null>(null);
  const [demoLoading, setDemoLoading] = useState(isPrecomputed);
  const [demoError, setDemoError] = useState<string | null>(null);

  useEffect(() => {
    if (!isPrecomputed) return;

    let cancelled = false;

    fetch('/demo/feature-examples.json')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load demo data (${res.status})`);
        return res.json();
      })
      .then((json) => {
        if (cancelled) return;
        setDemoFeatures(json.examples ?? []);
        setDemoMeta(json);
      })
      .catch((err) => {
        if (cancelled) return;
        setDemoError(err instanceof Error ? err.message : 'Failed to load demo data.');
      })
      .finally(() => {
        if (!cancelled) setDemoLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const fetchLiveFeature = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_BASE_URL}/features/${featureIdx}`);
      if (!res.ok) throw new Error(`Request failed (${res.status})`);
      const json = await res.json();
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed.');
    } finally {
      setLoading(false);
    }
  };

  const showPrecomputedFeature = (feature: DemoFeature) => {
    setData({ feature_idx: feature.feature_idx, examples: feature.top_examples });
  };

  return (
    <div className="pb-20">
      <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-10 py-10 mb-6">
        <h1 className="text-3xl font-bold text-white mb-2">Feature Browser</h1>
        <p className="text-neutral-400">Browse individual SAE features and their top-activating examples.</p>
      </div>

      {isPrecomputed && (
        <div className="rounded-xl border border-amber-800 bg-amber-500/[0.06] px-6 py-4 mb-6 text-sm text-amber-200">
          <strong>Precomputed demo.</strong> {demoMeta?.limitations ?? 'Showing a curated set of features generated by the real local PyTorch pipeline. Clone the repository to browse any of the 8,192 features live.'}
        </div>
      )}

      <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-10 py-8 mb-6">
        {isPrecomputed ? (
          <>
            {demoLoading && <div className="text-sm text-neutral-500">Loading demo features...</div>}

            {demoError && (
              <div className="rounded-lg border border-red-800 bg-red-500/[0.06] p-3 text-sm text-red-300">{demoError}</div>
            )}

            {!demoLoading && !demoError && demoFeatures.length === 0 && (
              <div className="text-sm text-neutral-500">No demo features available.</div>
            )}

            {!demoLoading && demoFeatures.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {demoFeatures.map((f) => (
                  <button
                    key={f.feature_idx}
                    onClick={() => showPrecomputedFeature(f)}
                    className="rounded-lg border border-neutral-700 bg-[#0c0916] hover:border-violet-700 hover:bg-violet-950/40 px-4 py-2.5 text-sm text-neutral-300 transition-colors"
                  >
                    #{f.feature_idx} — {f.label}
                  </button>
                ))}
              </div>
            )}
          </>
        ) : (
          <div className="flex gap-2">
            <input
              type="number"
              value={featureIdx}
              onChange={(e) => setFeatureIdx(e.target.value)}
              className="bg-[#0c0916] border border-neutral-700 rounded-lg px-4 py-2.5 w-40 text-neutral-200"
              placeholder="Feature index"
            />
            <button
              onClick={fetchLiveFeature}
              disabled={loading}
              className="bg-violet-950 border border-violet-800 hover:bg-violet-900/50 disabled:opacity-50 text-violet-300 rounded-lg px-5 py-2.5 text-sm font-medium transition-colors"
            >
              {loading ? 'Loading...' : 'Load Feature'}
            </button>
          </div>
        )}
      </div>

      {error && (
        <div className="rounded-xl border border-red-800 bg-red-500/[0.06] px-6 py-4 mb-6 text-sm text-red-300">{error}</div>
      )}

      {data && (
        <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-10 py-8">
          <h2 className="text-lg font-semibold text-white mb-5">
            Feature #{data.feature_idx} — Top Activating Examples
          </h2>
          <div className="space-y-2">
            {data.examples.map((ex, i) => (
              <div key={i} className="rounded-lg border border-neutral-800 bg-[#0c0916] p-4 flex gap-4">
                <span className="text-violet-400 font-mono w-16 shrink-0">{ex.activation.toFixed(2)}</span>
                <span className="text-neutral-400">{ex.context}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}