'use client';

import { useState, useEffect } from 'react';
import { API_BASE_URL, isPrecomputed } from '@/lib/runtime-config';

interface TokenLogEntry {
  step: number;
  token: string;
  score: number;
  eligible_for_alert: boolean;
  above_threshold: boolean;
  alert_active: boolean;
}

interface SafetyResult {
  generated_text: string;
  per_token_log: TokenLogEntry[];
  flagged: boolean;
  flagged_at_token: number | null;
  threshold: number;
  min_prefix_tokens: number;
  disclaimer: string;
}

interface DemoTrace {
  prompt: string;
  label: string;
  generated_text: string;
  flagged: boolean;
  flagged_at_token: number | null;
  per_token_log: TokenLogEntry[];
  note?: string;
}

const getErrorMessage = (detail: unknown, status: number): string => {
  if (typeof detail === 'string') return detail;
  if (Array.isArray(detail)) {
    return detail
      .map((item: unknown) => {
        if (typeof item === 'object' && item !== null && 'msg' in item && typeof item.msg === 'string') {
          return item.msg;
        }
        return 'Invalid request';
      })
      .join('; ');
  }
  return `Request failed (${status})`;
};

export default function SafetyMonitor() {
  const [prompt, setPrompt] = useState('The best way to deal with a difficult situation is');
  const [data, setData] = useState<SafetyResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [demoTraces, setDemoTraces] = useState<DemoTrace[]>([]);
  const [demoMeta, setDemoMeta] = useState<{ limitations?: string; threshold?: number; min_prefix_tokens?: number } | null>(null);
  const [demoLoading, setDemoLoading] = useState(isPrecomputed);
  const [demoError, setDemoError] = useState<string | null>(null);
  const [selectedTraceNote, setSelectedTraceNote] = useState<string | null>(null);

  useEffect(() => {
    if (!isPrecomputed) return;

    let cancelled = false;

    fetch('/demo/safety-traces.json')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load demo data (${res.status})`);
        return res.json();
      })
      .then((json) => {
        if (cancelled) return;
        setDemoTraces(json.traces ?? []);
        setDemoMeta(json);
      })
      .catch((err) => {
        if (cancelled) return;
        setDemoError(err instanceof Error ? err.message : 'Failed to load demo data.');
      })
      .finally(() => {
        if (!cancelled) setDemoLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const showPrecomputedTrace = (trace: DemoTrace) => {
    setData({
      generated_text: trace.generated_text,
      per_token_log: trace.per_token_log,
      flagged: trace.flagged,
      flagged_at_token: trace.flagged_at_token,
      threshold: demoMeta?.threshold ?? 0,
      min_prefix_tokens: demoMeta?.min_prefix_tokens ?? 0,
      disclaimer: demoMeta?.limitations ?? '',
    });
    setSelectedTraceNote(trace.note ?? null);
  };

  const runLiveMonitor = async () => {
    if (!prompt.trim()) {
      setError('Enter a prompt first.');
      return;
    }

    setLoading(true);
    setError(null);
    setData(null);
    setSelectedTraceNote(null);

    try {
      const res = await fetch(`${API_BASE_URL}/safety/monitor`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: prompt.trim(), max_new_tokens: 30 }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error(getErrorMessage(body?.detail, res.status));
      }

      const json: SafetyResult = await res.json();
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'The monitor request failed.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="pb-20">
      <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-5 sm:px-10 py-8 sm:py-10 mb-6">
        <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">
          Safety Monitor {isPrecomputed ? '(Precomputed Demo)' : '(Experimental)'}
        </h1>
        <p className="text-neutral-400 text-sm sm:text-base">A live, per-token safety probe over 100 SAE features.</p>
      </div>

      <div className="rounded-xl border border-amber-800 bg-amber-500/[0.06] px-5 sm:px-6 py-4 mb-6 text-sm text-amber-200">
        <strong>Experimental prototype, not a production safety system.</strong>{' '}
        {isPrecomputed
          ? (demoMeta?.limitations ?? 'These traces were generated by the real local PyTorch/FastAPI pipeline and bundled for reliable browser viewing. Clone the repository to run live inference on custom prompts.')
          : 'This computes the monitor token-by-token internally, but shows the full trace after generation finishes — a per-token trace, not a live-streaming UI. Expect frequent false alarms on benign text.'}
      </div>

      <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-5 sm:px-10 py-8 mb-6">
        {isPrecomputed ? (
          <>
            {demoLoading && <div className="text-sm text-neutral-500">Loading demo traces...</div>}

            {demoError && (
              <div className="rounded-lg border border-red-800 bg-red-500/[0.06] p-3 text-sm text-red-300">{demoError}</div>
            )}

            {!demoLoading && !demoError && demoTraces.length === 0 && (
              <div className="text-sm text-neutral-500">No demo traces available.</div>
            )}

            {!demoLoading && demoTraces.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {demoTraces.map((t, i) => (
                  <button
                    key={i}
                    onClick={() => showPrecomputedTrace(t)}
                    className="rounded-lg border border-neutral-700 bg-[#0c0916] hover:border-violet-700 hover:bg-violet-950/40 px-4 py-2.5 text-sm text-neutral-300 text-left transition-colors"
                  >
                    {t.label}
                  </button>
                ))}
              </div>
            )}
          </>
        ) : (
          <>
            {error && (
              <div className="rounded-lg border border-red-800 bg-red-500/[0.06] p-3 text-sm text-red-300 mb-4">{error}</div>
            )}

            <div className="flex flex-col sm:flex-row gap-2">
              <input
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="bg-[#0c0916] border border-neutral-700 rounded-lg px-4 py-2.5 flex-1 text-neutral-200"
                placeholder="Enter a prompt..."
              />
              <button
                onClick={runLiveMonitor}
                disabled={loading}
                className="bg-violet-950 border border-violet-800 hover:bg-violet-900/50 disabled:opacity-50 text-violet-300 rounded-lg px-5 py-2.5 text-sm font-medium whitespace-nowrap transition-colors"
              >
                {loading ? 'Generating...' : 'Run Monitor'}
              </button>
            </div>
          </>
        )}
      </div>

      {selectedTraceNote && (
        <div className="rounded-xl border border-amber-800 bg-amber-500/[0.06] px-5 sm:px-6 py-4 mb-6 text-sm text-amber-200">
          {selectedTraceNote}
        </div>
      )}

      {data && (
        <div className="rounded-2xl border border-neutral-800 bg-[#100c1a] px-5 sm:px-10 py-8">
          <div className="rounded-lg border border-neutral-800 bg-[#0c0916] px-5 py-3 mb-5 flex flex-wrap gap-x-4 gap-y-1">
            <span className={data.flagged ? 'text-red-400 font-semibold' : 'text-emerald-400 font-semibold'}>
              {data.flagged ? `⚠ Alert triggered at token ${data.flagged_at_token}` : '✓ No alert triggered'}
            </span>
            <span className="text-neutral-500 text-sm font-mono">
              threshold={data.threshold.toFixed(4)} · min_prefix={data.min_prefix_tokens}
            </span>
          </div>

          <p className="text-neutral-300 mb-6 whitespace-pre-wrap text-sm sm:text-base">{data.generated_text}</p>

          <h2 className="text-lg font-semibold text-white mb-4">Per-token trace</h2>
          <div className="space-y-1.5 overflow-x-auto">
            {data.per_token_log.map((entry) => (
              <div
                key={entry.step}
                className={`flex gap-4 p-2.5 rounded-lg border text-xs sm:text-sm min-w-[420px] ${
                  entry.alert_active
                    ? 'bg-red-500/[0.08] border-red-900'
                    : 'bg-[#0c0916] border-neutral-800'
                }`}
              >
                <span className="w-8 text-neutral-600">{entry.step}</span>
                <span className="w-24 font-mono whitespace-pre text-neutral-300">{JSON.stringify(entry.token)}</span>
                <span className="w-20 text-violet-400 font-mono">{entry.score.toFixed(4)}</span>
                <span className="text-neutral-500">
                  {!entry.eligible_for_alert ? 'not yet eligible' : entry.above_threshold ? 'above threshold' : 'below threshold'}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}