'use client';

import { useState, useEffect } from 'react';
import { API_BASE_URL, isPrecomputed } from '@/lib/runtime-config';

interface TokenLogEntry {
  step: number;
  token: string;
  score: number;
  eligible_for_alert: boolean;
  above_threshold: boolean;
  alert_active: boolean;
}

interface SafetyResult {
  generated_text: string;
  per_token_log: TokenLogEntry[];
  flagged: boolean;
  flagged_at_token: number | null;
  threshold: number;
  min_prefix_tokens: number;
  disclaimer: string;
}

interface DemoTrace {
  prompt: string;
  generated_text: string;
  flagged: boolean;
  flagged_at_token: number;
  per_token_log: TokenLogEntry[];
  note?: string;
}

const getErrorMessage = (detail: unknown, status: number): string => {
  if (typeof detail === 'string') return detail;
  if (Array.isArray(detail)) {
    return detail
      .map((item: unknown) => {
        if (typeof item === 'object' && item !== null && 'msg' in item && typeof item.msg === 'string') {
          return item.msg;
        }
        return 'Invalid request';
      })
      .join('; ');
  }
  return `Request failed (${status})`;
};

export default function SafetyMonitor() {
  const [prompt, setPrompt] = useState('The best way to deal with a difficult situation is');
  const [data, setData] = useState<SafetyResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [demoTraces, setDemoTraces] = useState<DemoTrace[]>([]);
  const [demoMeta, setDemoMeta] = useState<{ limitations?: string; threshold?: number; min_prefix_tokens?: number } | null>(null);
  const [demoLoading, setDemoLoading] = useState(isPrecomputed);
  const [demoError, setDemoError] = useState<string | null>(null);
  const [selectedTraceNote, setSelectedTraceNote] = useState<string | null>(null);

  useEffect(() => {
    if (!isPrecomputed) return;

    let cancelled = false;

    fetch('/demo/safety-traces.json')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load demo data (${res.status})`);
        return res.json();
      })
      .then((json) => {
        if (cancelled) return;
        setDemoTraces(json.traces ?? []);
        setDemoMeta(json);
      })
      .catch((err) => {
        if (cancelled) return;
        setDemoError(err instanceof Error ? err.message : 'Failed to load demo data.');
      })
      .finally(() => {
        if (!cancelled) setDemoLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const showPrecomputedTrace = (trace: DemoTrace) => {
    setData({
      generated_text: trace.generated_text,
      per_token_log: trace.per_token_log,
      flagged: trace.flagged,
      flagged_at_token: trace.flagged_at_token,
      threshold: demoMeta?.threshold ?? 0,
      min_prefix_tokens: demoMeta?.min_prefix_tokens ?? 0,
      disclaimer: demoMeta?.limitations ?? '',
    });
    setSelectedTraceNote(trace.note ?? null);
  };

  const runLiveMonitor = async () => {
    if (!prompt.trim()) {
      setError('Enter a prompt first.');
      return;
    }

    setLoading(true);
    setError(null);
    setData(null);
    setSelectedTraceNote(null);

    try {
      const res = await fetch(`${API_BASE_URL}/safety/monitor`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: prompt.trim(), max_new_tokens: 30 }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error(getErrorMessage(body?.detail, res.status));
      }

      const json: SafetyResult = await res.json();
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'The monitor request failed.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 p-8">
      <h1 className="text-2xl font-bold mb-2">
        ActivationLens — Safety Monitor Trace {isPrecomputed ? '(Precomputed Demo)' : '(Experimental)'}
      </h1>

      <div className="bg-yellow-950 border border-yellow-700 rounded p-4 mb-6 text-sm text-yellow-200">
        <strong>Experimental prototype, not a production safety system.</strong>{' '}
        {isPrecomputed
          ? (demoMeta?.limitations ?? 'These traces were generated by the real local PyTorch/FastAPI pipeline and bundled for reliable browser viewing. Clone the repository to run live inference on custom prompts.')
          : 'This computes the monitor token-by-token internally, but shows the full trace after generation finishes — a per-token trace, not a live-streaming UI. Expect frequent false alarms on benign text.'}
      </div>

      {isPrecomputed ? (
        <>
          {demoLoading && <div className="mb-8 text-sm text-neutral-500">Loading demo traces...</div>}

          {demoError && (
            <div className="mb-8 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">{demoError}</div>
          )}

          {!demoLoading && !demoError && demoTraces.length === 0 && (
            <div className="mb-8 text-sm text-neutral-500">No demo traces available.</div>
          )}

          {!demoLoading && demoTraces.length > 0 && (
            <div className="flex flex-wrap gap-2 mb-8">
              {demoTraces.map((t, i) => (
                <button
                  key={i}
                  onClick={() => showPrecomputedTrace(t)}
                  className="bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 rounded px-3 py-2 text-sm text-left"
                >
                  &quot;{t.prompt.slice(0, 40)}...&quot;
                </button>
              ))}
            </div>
          )}
        </>
      ) : (
        <>
          {error && (
            <div className="mb-6 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">{error}</div>
          )}

          <div className="flex gap-2 mb-8">
            <input
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="bg-neutral-800 border border-neutral-700 rounded px-3 py-2 flex-1"
              placeholder="Enter a prompt..."
            />
            <button
              onClick={runLiveMonitor}
              disabled={loading}
              className="bg-blue-600 hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-50 rounded px-4 py-2 font-medium whitespace-nowrap"
            >
              {loading ? 'Generating...' : 'Run Monitor'}
            </button>
          </div>
        </>
      )}

      {selectedTraceNote && (
        <div className="mb-4 rounded border border-amber-800 bg-amber-950 p-3 text-sm text-amber-200">
          {selectedTraceNote}
        </div>
      )}

      {data && (
        <div>
          <div className="mb-4 p-3 rounded bg-neutral-900 border border-neutral-800">
            <span className={data.flagged ? 'text-red-400 font-semibold' : 'text-green-400 font-semibold'}>
              {data.flagged ? `⚠ Alert triggered at token ${data.flagged_at_token}` : '✓ No alert triggered'}
            </span>
            <span className="text-neutral-400 ml-4 text-sm">
              threshold={data.threshold.toFixed(4)} | min_prefix={data.min_prefix_tokens}
            </span>
          </div>

          <p className="text-neutral-300 mb-6 whitespace-pre-wrap">{data.generated_text}</p>

          <h2 className="text-lg font-semibold mb-3">Per-token trace</h2>
          <div className="space-y-1">
            {data.per_token_log.map((entry) => (
              <div
                key={entry.step}
                className={`flex gap-4 p-2 rounded border text-sm ${
                  entry.alert_active ? 'bg-red-950 border-red-800' : 'bg-neutral-900 border-neutral-800'
                }`}
              >
                <span className="w-8 text-neutral-500">{entry.step}</span>
                <span className="w-24 font-mono whitespace-pre">{JSON.stringify(entry.token)}</span>
                <span className="w-20 text-blue-400 font-mono">{entry.score.toFixed(4)}</span>
                <span className="text-neutral-500">
                  {!entry.eligible_for_alert ? 'not yet eligible' : entry.above_threshold ? 'above threshold' : 'below threshold'}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </main>
  );
}