'use client';

import { useState, useEffect } from 'react';
import { API_BASE_URL, isPrecomputed } from '@/lib/runtime-config';

interface FeatureExample {
  activation: number;
  context: string;
}

interface DemoFeature {
  feature_idx: number;
  label: string;
  top_examples: FeatureExample[];
}

export default function Home() {
  const [featureIdx, setFeatureIdx] = useState('500');
  const [data, setData] = useState<{ feature_idx: number; examples: FeatureExample[] } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [demoFeatures, setDemoFeatures] = useState<DemoFeature[]>([]);
  const [demoMeta, setDemoMeta] = useState<{ limitations?: string } | null>(null);
  const [demoLoading, setDemoLoading] = useState(isPrecomputed);
  const [demoError, setDemoError] = useState<string | null>(null);

  useEffect(() => {
    if (!isPrecomputed) return;

    let cancelled = false;

    fetch('/demo/feature-examples.json')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load demo data (${res.status})`);
        return res.json();
      })
      .then((json) => {
        if (cancelled) return;
        setDemoFeatures(json.examples ?? []);
        setDemoMeta(json);
      })
      .catch((err) => {
        if (cancelled) return;
        setDemoError(err instanceof Error ? err.message : 'Failed to load demo data.');
      })
      .finally(() => {
        if (!cancelled) setDemoLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const fetchLiveFeature = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_BASE_URL}/features/${featureIdx}`);
      if (!res.ok) throw new Error(`Request failed (${res.status})`);
      const json = await res.json();
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed.');
    } finally {
      setLoading(false);
    }
  };

  const showPrecomputedFeature = (feature: DemoFeature) => {
    setData({ feature_idx: feature.feature_idx, examples: feature.top_examples });
  };

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 p-8">
      <h1 className="text-2xl font-bold mb-2">ActivationLens — Feature Browser</h1>

      {isPrecomputed && (
        <div className="bg-yellow-950 border border-yellow-700 rounded p-4 mb-6 text-sm text-yellow-200">
          <strong>Precomputed demo.</strong> {demoMeta?.limitations ?? 'Showing a curated set of features generated by the real local PyTorch pipeline. Clone the repository to browse any of the 8,192 features live.'}
        </div>
      )}

      {isPrecomputed ? (
        <>
          {demoLoading && (
            <div className="mb-8 text-sm text-neutral-500">Loading demo features...</div>
          )}

          {demoError && (
            <div className="mb-8 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">
              {demoError}
            </div>
          )}

          {!demoLoading && !demoError && demoFeatures.length === 0 && (
            <div className="mb-8 text-sm text-neutral-500">No demo features available.</div>
          )}

          {!demoLoading && demoFeatures.length > 0 && (
            <div className="flex flex-wrap gap-2 mb-8">
              {demoFeatures.map((f) => (
                <button
                  key={f.feature_idx}
                  onClick={() => showPrecomputedFeature(f)}
                  className="bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 rounded px-3 py-2 text-sm"
                >
                  #{f.feature_idx} — {f.label}
                </button>
              ))}
            </div>
          )}
        </>
      ) : (
        <div className="flex gap-2 mb-8">
          <input
            type="number"
            value={featureIdx}
            onChange={(e) => setFeatureIdx(e.target.value)}
            className="bg-neutral-800 border border-neutral-700 rounded px-3 py-2 w-40"
            placeholder="Feature index"
          />
          <button
            onClick={fetchLiveFeature}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded px-4 py-2 font-medium"
          >
            {loading ? 'Loading...' : 'Load Feature'}
          </button>
        </div>
      )}

      {error && (
        <div className="mb-6 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">{error}</div>
      )}

      {data && (
        <div>
          <h2 className="text-lg font-semibold mb-4">
            Feature #{data.feature_idx} — Top Activating Examples
          </h2>
          <div className="space-y-2">
            {data.examples.map((ex, i) => (
              <div key={i} className="bg-neutral-900 border border-neutral-800 rounded p-3 flex gap-4">
                <span className="text-blue-400 font-mono w-20 shrink-0">{ex.activation.toFixed(2)}</span>
                <span className="text-neutral-300">{ex.context}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </main>
  );
}